In [13]:
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.keys import Keys
import pandas as pd
import time
from bs4 import BeautifulSoup
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
from selenium.webdriver.chrome.options import Options
from selenium.webdriver.chrome.service import Service

In [14]:
from selenium import webdriver

driver=webdriver.Chrome()

driver.get("https://catalog.onliner.by/mobile")

In [15]:
# Собираем все ссылки на объявления с выбранной страницы
def get_all_links_on_page():
    elements = driver.find_elements(By.CLASS_NAME, value='catalog-form__link')
    # elements = driver.find_elements(by=By.CSS_SELECTOR, value="#container > div > div > div > div > div.catalog-content > div.catalog-wrapper > div > div > div.catalog-form__tabs > div > div > div > div > div.catalog-form__filter-part.catalog-form__filter-part_2 > div.catalog-form__offers > div > div:nth-child(1) > div > div > div.catalog-form__offers-part.catalog-form__offers-part_data > div.catalog-form__description.catalog-form__description_primary.catalog-form__description_base-additional.catalog-form__description_font-weight_semibold.catalog-form__description_condensed-other > a")
    # <a href="https://catalog.onliner.by/mobile/xiaomi/redmi15c8256ebk" class="catalog-form__link catalog-form__link_primary-additional catalog-form__link_base-additional catalog-form__link_font-weight_semibold catalog-form__link_nodecor"> Телефон Xiaomi Redmi 15C 4G 8GB/256GB международная версия (черный) </a>
    ads_list = []
    for element in elements:
        ads_list.append(element.get_attribute('href'))
        # print(element.get_attribute('href'), '\n')

    return ads_list

In [12]:
links = get_all_links_on_page()

NameError: name 'By' is not defined

In [11]:
links

NameError: name 'links' is not defined

In [34]:
# Переход на следующую страницу через нажатие на кнопку
def click_next_page():
    clickable_element = WebDriverWait(driver, 10).until(
        EC.element_to_be_clickable((By.XPATH, '/html/body/div[2]/div/div/div/div/div/div/div/div/div[2]/div[1]/div/div/div[4]/div/div/div/div/div[3]/div[3]/a'))
    )

    clickable_element.click()

In [35]:
click_next_page()

In [36]:
len(links)

21

In [37]:
clear_links = []

for item in links:
    if item == None or 'forum.' in item or 'tech.' in item:
        pass
    else:
        clear_links.append(item)

len(clear_links)

13

In [85]:
very_clear_links = []

for item in clear_links:
    if 'prices' in item or 'reviews' in item or 'used' in item:
        pass
    else:
        very_clear_links.append(item)

len(very_clear_links)

6

In [33]:
def clean_links(links: list):
    print(f'Start size of links list: {len(links)}')
    clear_links = []
    very_clear_links = []

    for item in links:
        if item == None or 'forum.' in item or 'tech.' in item:
            pass
        else:
            clear_links.append(item)
    print(f'Current size of links list: {len(clear_links)}')

    for item in clear_links:
        if 'prices' in item or 'reviews' in item or 'used' in item:
            pass
        else:
            very_clear_links.append(item)
    print(f'Finish size of links list: {len(very_clear_links)}')

    return very_clear_links

In [87]:
very_clear_links

['https://catalog.onliner.by/mobile/xiaomi/note17prom8256wt',
 'https://catalog.onliner.by/mobile/apple/ip18pro256bu',
 'https://catalog.onliner.by/mobile/apple/iphoneduo256ns',
 'https://catalog.onliner.by/mobile/apple/iphone17256bk',
 'https://catalog.onliner.by/mobile/samsung/sms731b8256bk',
 'https://catalog.onliner.by/mobile/apple/ip18promax256sl']

In [34]:
links_list = []
try:
    for iter in range(0, 5, 1):
        links_list += get_all_links_on_page()
        click_next_page()
except:
    print("All done")
    clean_links_list = clean_links(links_list)
finally:
    print("All done")
    clean_links_list = clean_links(links_list)

All done
Start size of links list: 0
Current size of links list: 0
Finish size of links list: 0
All done
Start size of links list: 0
Current size of links list: 0
Finish size of links list: 0

In [35]:
clean_links_list

[]

In [36]:
with open('links.txt', 'a', encoding='utf-8') as file:
    for link in clean_links_list:
        file.write(link +'\n')

In [17]:
def get_characteristics():
    character_dict={}
    elements= driver.find_elements(By.CLASS_NAME, value='product-specs__table')
    for item in elements:
            tds=item.find_elements(By.TAG_NAME, value='td')
            for i in range(0, len(tds)-2):
                if tds[i].rect['width'] == 453:
                    character_dict.update({tds[i].text:tds[i+1].text})
    print(character_dict)


get_characteristics()

{}

In [63]:
def get_characteristics():
    character_dict=[]
    character_dict.append({'Название модели': driver.find_element(By.CLASS_NAME, value='catalog-masthead__title').text})
    elements= driver.find_elements(By.CSS_SELECTOR, value='.product-specs__table tr')
    for item in elements:
            tds = item.find_elements(By.TAG_NAME, value='td')
            if len(tds) == 2:
                if not tds[1].text:
                    if tds[1].find_elements(By.CLASS_NAME, value='i-x'):
                        character_dict.append({tds[0].text:'No'})
                    else:
                        character_dict.append({tds[0].text:'Yes'})
                else:
                    character_dict.append({tds[0].text:tds[1].text})


    return character_dict

In [92]:

clean_links_list = []
with open ('links.txt', 'r', encoding='utf_8') as l:
    while True:
        line = l.readline()
        clean_links_list.append(line)
        if not line:
            break
print(len(clean_links_list))

table=pd.DataFrame()
for link in clean_links_list[0:5]:
    driver.get(link)
    new_row=pd.DataFrame([get_characteristics()])
    table= pd.concat([table, new_row], ignore_index=True)
table

139

,0,1,2,3,4,5,6,7,8,9,...,99,100,101,102,103,104,105,106,107,108
0,{'Название модели': 'Телефон Samsung Galaxy S2...,{'Дата выхода на рынок': '2025 г.'},{'Отличия от предыдущего поколения': '✅ Произв...,{'Операционная система': 'Android'},{'Версия ОС на момент выхода': 'Android 15'},{'Оболочка': 'One UI (7)'},"{'Размер экрана': '6.2""'}",{'Разрешение экрана': '1080x2340'},{'Технология экрана': 'AMOLED (Dynamic AMOLED ...,{'Частота обновления экрана': '120 Гц'},...,{'Мощность зарядки': '25 Вт'},"{'Комплект поставки': 'кабель USB-C - USB-C, с...",{'Чехол': 'No'},{'Модель': 'Samsung Galaxy S25'},{'Поддержка обновлений ОС (с момента выхода)':...,"{'Метки': 'Onliner рекомендует, флагман, игров...",NaN,NaN,NaN,NaN
1,{'Название модели': 'Телефон Apple iPhone 15 P...,{'Дата выхода на рынок': '2023 г.'},{'Отличия от предыдущего поколения': '✅ Дизайн...,{'Операционная система': 'iOS'},{'Версия ОС на момент выхода': 'iOS 17'},"{'Размер экрана': '6.1""'}",{'Разрешение экрана': '1179x2556'},{'Технология экрана': 'OLED (Super Retina XDR)'},{'Частота обновления экрана': '120 Гц'},{'Объем оперативной памяти': '8 ГБ'},...,{'Модель': 'Apple iPhone 15 Pro'},"{'Метки': 'флагман, игровой, 128 ГБ, водонепро...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,{'Название модели': 'Телефон Google Pixel 11 1...,{'Дата выхода на рынок': '2026 г.'},{'Операционная система': 'Android'},{'Версия ОС на момент выхода': 'Android 17'},{'Оболочка': 'Android без оболочки'},"{'Размер экрана': '6.3""'}",{'Разрешение экрана': '1080x2424'},{'Технология экрана': 'OLED (Actua)'},{'Частота обновления экрана': '120 Гц'},{'Объем оперативной памяти': '12 ГБ'},...,"{'Комплект поставки': 'кабель USB-C - USB-C, с...",{'Чехол': 'No'},{'Перо (стилус)': 'No'},{'Модель': 'Google Pixel 11'},{'Поддержка обновлений ОС (с момента выхода)':...,"{'Метки': 'Onliner рекомендует, 256 ГБ, водоне...",NaN,NaN,NaN,NaN
3,{'Название модели': 'Телефон Samsung Galaxy A5...,{'Дата выхода на рынок': '2026 г.'},{'Операционная система': 'Android'},{'Версия ОС на момент выхода': 'Android 16'},{'Оболочка': 'One UI'},"{'Размер экрана': '6.7""'}",{'Разрешение экрана': '1080x2340'},{'Технология экрана': 'AMOLED (Super AMOLED+)'},{'Частота обновления экрана': '120 Гц'},{'Объем оперативной памяти': '8 ГБ'},...,{'Модель': 'Samsung Galaxy A57'},{'Поддержка обновлений ОС (с момента выхода)':...,"{'Метки': 'Onliner рекомендует, 256 ГБ, водоне...",NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,{'Название модели': 'Телефон Samsung Galaxy Z ...,{'Дата выхода на рынок': '2026 г.'},{'Отличия от предыдущего поколения': '✅ Корпус...,{'Операционная система': 'Android'},{'Версия ОС на момент выхода': 'Android 17'},{'Оболочка': 'One UI'},"{'Размер экрана': '7.6""'}",{'Разрешение экрана': '1848x2448'},{'Технология экрана': 'AMOLED (Dynamic AMOLED ...,{'Частота обновления экрана': '120 Гц'},...,{'Емкость аккумулятора': '4 800 мА·ч'},{'Конструкция аккумулятора': 'несъемный'},{'Макс. время воспроизведения видео': '26 ч'},{'Мощность зарядки': '45 Вт'},"{'Комплект поставки': 'кабель USB-C - USB-C, с...",{'Чехол': 'No'},{'Перо (стилус)': 'No'},{'Модель': 'Samsung Galaxy Z Fold8'},{'Поддержка обновлений ОС (с момента выхода)':...,"{'Метки': 'Onliner рекомендует, флагман, 256 Г..."

In [ ]:
table.shape[1]

(5, 109)

In [89]:

lonest_str_index = 0
for i in range(0, table.shape[0]):
    if str(table[(table.shape[1]) -1 ][i]) != "nan":
        lonest_str_index = i

In [90]:

colmn_name=[]
for item in  table.loc[lonest_str_index]:
    for key, _ in item.items():
        colmn_name.append(key)

df= pd.DataFrame(columns=colmn_name)
df

Empty DataFrame
Columns: [Название модели, Дата выхода на рынок, Отличия от предыдущего поколения, Операционная система, Версия ОС на момент выхода, Оболочка, Размер экрана, Разрешение экрана, Технология экрана, Частота обновления экрана, Объем оперативной памяти, Объем встроенной памяти, Количество точек матрицы основной камеры, Характеристики блока камер, Максимальное разрешение видео, Беспроводная зарядка, Обратная беспроводная зарядка, Быстрая зарядка, Поддержка карт памяти, Количество физических SIM-карт, Формат SIM-карты, Платформа, Процессор, Тактовая частота процессора, Количество ядер, Микроархитектура ЦПУ, Разрядность процессора, Техпроцесс, Графический ускоритель, Конструкция корпуса, Стереодинамики, Материал граней, Материал задней крышки, Цвет граней, Цвет задней крышки, Цвет фронтальной панели, Ударопрочный корпус, Пыле- и влагозащита, Встроенные магниты (для зарядки и аксессуаров), Физическая QWERTY-клавиатура, Сканер отпечатка пальца, Расположение сканера отпечатка пальца, Разблокировка по лицу, Функциональные особенности, Размеры складных устройств, Вес, Количество цветов экрана, Разрешающая способность экрана, Соотношение сторон, Яркость экрана (пиковая), Защита от царапин, Динамический контроль частоты обновления (LTPO), Технология экрана, Размер экрана, Разрешение экрана, Частота обновления экрана, Количество цветов экрана, Разрешающая способность экрана, Яркость экрана (пиковая), Защита от царапин, Постоянная работа экрана, Динамический контроль частоты обновления (LTPO), Основной блок камер, Количество модулей камеры, Модули камер, Встроенная вспышка, Автоматическая фокусировка, Тип стабилизации, Цифровой зум, Диафрагма основной камеры, Макс. количество кадров в секунду, Фронтальная камера, Характеристики фронтальной камеры, Расположение фронтальной камеры, Двойная камера, Автоматическая фокусировка, Встроенная вспышка, Диафрагма фронтальной камеры, Макс. разрешение видео фронтальной камеры, Акселерометр, Гироскоп, Датчик освещенности, Датчик приближения, Барометр, Монитор сердечного ритма, Измерение насыщенности крови кислородом, GPS, ГЛОНАСС, Beidou, GALILEO, Поддержка 5G, Поддерживаемые частоты и полосы, Bluetooth, Аудиокодеки Bluetooth, Аудиовыход, Wi-Fi, Разъём подключения, NFC, Тип аккумулятора, Емкость аккумулятора, ...]
Index: []

[0 rows x 109 columns]